# Radium Alacritty Theme

[colors.primary]
foreground = "#d4d4d5"
background = "#0a0d11"
dim_foreground = "#525559"
bright_foreground = "#d4d4d5"

[colors.cursor]
text = "#0a0d11"
cursor = "#d4d4d5"

[colors.vi_mode_cursor]
text = "#0a0d11"
cursor = "#7ab0df"

[colors.search.matches]
foreground = "#d4d4d5"
background = "#191d22"

[colors.search.focused_match]
foreground = "#0a0d11"
background = "#ffe59e"

[colors.hints.start]
foreground = "#d4d4d5"
background = "#191d22"

[colors.hints.end]
foreground = "#d4d4d5"
background = "#191d22"

[colors.line_indicator]
foreground = "None"
background = "None"

[colors.footer_bar]
foreground = "#d4d4d5"
background = "#191d22"

[colors.selection]
text = "#d4d4d5"
background = "#191d22"

[colors.normal]
black   = "#0a0d11"
red     = "#f87070"
green   = "#27d99e"
yellow  = "#ffe59e"
blue    = "#7ab0df"
magenta = "#c397d8"
cyan    = "#50cad2"
white   = "#525559"

[colors.bright]
black   = "#191d22"
red     = "#ff8e8e"
green   = "#79dcaa"
yellow  = "#ffeda6"
blue    = "#87bdec"
magenta = "#b68acb"
cyan    = "#63b3ad"
white   = "#d4d4d5"

[colors.dim]
black   = "#111519"
red     = "#c85c5c"
green   = "#2e9a76"
yellow  = "#eecb84"
blue    = "#6896c1"
magenta = "#ab83bc"
cyan    = "#49a5ac"
white   = "#424447"
