# Radium Starship Config
format = """
[](color_orange)\
$os\
$username\
[](bg:color_yellow fg:color_orange)\
$directory\
[](fg:color_yellow bg:color_aqua)\
$git_branch\
$git_status\
[](fg:color_aqua bg:color_blue)\
[](fg:color_blue bg:color_bg3)\
$docker_context\
$conda\
$pixi\
[](fg:color_bg3 bg:color_bg1)\
$time\
[ ](fg:color_bg1)\
$line_break$character"""

# Switched to the new radium palette
palette = 'radium'

# Radium Palette Definition
[palettes.radium]
color_fg0    = '#d4d4d5'  # foreground
color_bg1    = '#0a0d11'  # main background
color_bg3    = '#191d22'  # secondary background
color_blue   = '#7ab0df'  # blue
color_green  = '#27d99e'  # green
color_aqua   = '#50cad2'  # cyan
color_orange = '#ffe59e'  # yellow (placeholder for orange)
color_purple = '#c397d8'  # purple
color_red    = '#f87070'  # red
color_yellow = '#ffe59e'  # yellow

[os]
disabled = false
style = "bg:color_orange fg:color_bg1" # Use color_bg1 for better contrast on yellow

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color_orange fg:color_bg1" # Use color_bg1 for better contrast
style_root = "bg:color_orange fg:color_bg1" # Use color_bg1 for better contrast
format = '[ ]($style)'

[directory]
style = "fg:color_bg1 bg:color_yellow" # Use color_bg1 for better contrast
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color_aqua"
format = '[[ $symbol $branch ](fg:color_bg1 bg:color_aqua)]($style)' # Use color_bg1

[git_status]
style = "bg:color_aqua"
format = '[[($all_status$ahead_behind )](fg:color_bg1 bg:color_aqua)]($style)' # Use color_bg1

[time]
disabled = false
use_12hr = false
time_format = "%H:%M"
style = "bg:color_bg1"
format = '[[  $time ](fg:color_fg0 bg:color_bg1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:color_green)'
error_symbol = '[](bold fg:color_red)'
vimcmd_symbol = '[](bold fg:color_green)'
vimcmd_replace_one_symbol = '[](bold fg:color_purple)'
vimcmd_replace_symbol = '[](bold fg:color_purple)'
vimcmd_visual_symbol = '[](bold fg:color_yellow)'
